hw-02
NataliiaValko/goit-nodejs-rest-api pull request #1
Opened 2021-10-30 22:24 UTC by NataliiaValko

Hello, Vlad. I hope you have a good time =)

2021-11-02 00:40 UTC, TViglesGoom requested changes

2021-11-02 00:40 UTC, TViglesGoom commented on helpers/sendErrorReqToRes.js
> +// const { BadRequest } = require('http-errors')
Подчищаем за собой комментарии кода

2021-11-02 00:40 UTC, TViglesGoom commented on helpers/sendErrorIdToRes.js
> +  throw new NotFound(`Contact with id '${contactId}' not found`)
Функция, которая возвращает ошибку? Да ещё и подписана, что будет что-то отправлять.

2021-11-02 00:40 UTC, TViglesGoom commented on helpers/sendErrorReqToRes.js
> +module.exports = sendErrorReqToRes
А вам точно для этого нужна отдельная функция в отдельном файле?

2021-11-02 00:40 UTC, TViglesGoom commented on helpers/sendSuccessToRes.js
> +module.exports = sendSuccessRes
Вот честно скажу, никогда не видел, чтобы это выносили в отдельную функцию. Это кто вам такое показал?

2021-11-02 00:40 UTC, TViglesGoom commented on helpers/sendErrorReqToRes.js
> +module.exports = sendErrorReqToRes
А ошибка, получается, бывает только со статусом 400?

2021-11-02 00:40 UTC, TViglesGoom commented on models/contacts/updateById.js
> +  // console.table(await getAll())
Убирайте комментариии кода!

2021-11-02 00:40 UTC, TViglesGoom commented on models/contacts/removeById.js
> +const handlerIncorrectId = require('./handlerIncorrectId')
Нейминг. Это переводится "Обработчик некорректный айди". Наверное, имелось ввиду "handle"?

2021-11-02 00:40 UTC, TViglesGoom commented on routes/api/contacts/contacts.js
> +  validation(contactSchema),
Тут поля required все, а по тз мы можем только обновлённые давать.

2021-11-02 00:40 UTC, TViglesGoom commented on models/contacts/updateById.js
> +  const index = contacts.findIndex((contact) => contact.id.toString() === id)
А в чём проблема не приводить id к строке на каждой итерации? Мы не знаем, какой там лежит тип данных?

2021-11-02 00:40 UTC, TViglesGoom commented on models/contacts/removeById.js
> +  const index = contacts.findIndex((contact) => contact.id.toString() === id)
А в чём проблема не приводить id к строке на каждой итерации? Мы не знаем, какой там лежит тип данных?

2021-11-02 00:40 UTC, TViglesGoom commented on models/contacts/removeById.js
> +    return handlerIncorrectId()
handle*

2021-11-02 00:40 UTC, TViglesGoom commented on models/contacts/handlerIncorrectId.js
> +      'You entered incorrectly ID. Please check your ID and repeat the request!'
Incorrectly - наречие. Incorrect - прилагательное.

2021-11-02 00:40 UTC, TViglesGoom commented on models/contacts/getById.js
> +    (contact) => contact.id.toString() === id.toString()
А в чём проблема не приводить id к строке на каждой итерации? Мы не знаем, какой там лежит тип данных?

2021-11-02 00:40 UTC, TViglesGoom commented on models/contacts/getAll.js
> +  const contacts = JSON.parse(data)
Лишние переменные. Для чего? сразу возвращайте `JSON.parse(data)`. Я бы вообще это написал `async () => JSON.parse(await fs.readFile(contactsDataPath))`

2021-11-02 09:31 UTC, NataliiaValko commented on helpers/sendErrorIdToRes.js
> +  throw new NotFound(`Contact with id '${contactId}' not found`)
С неймингом ок, переименую. На счет того, то создает ошибку....так этот кусок кода переиспользуемый, он 3 раза используется в разных местах. Создать переиспользуемую функцию для оптимизации тут не правильно?

2021-11-02 09:31 UTC, NataliiaValko commented on helpers/sendErrorReqToRes.js
> +// const { BadRequest } = require('http-errors')
+

2021-11-02 17:11 UTC, NataliiaValko commented on helpers/sendErrorReqToRes.js
> +module.exports = sendErrorReqToRes
Именно эта ошибка, да, только со статусом 400, потому что она будет в респонсе при невалидном/неполном реквесте.

2021-11-02 17:14 UTC, NataliiaValko commented on helpers/sendSuccessToRes.js
> +module.exports = sendSuccessRes
Увидела у преподавателя, и честно скажу, мне оч нравится эта идея. Зачем 6 раз писать один и тот же код? Эта часть кода используется в каждом контроллере! Создать переиспользуемую функцию для оптимизации тут не правильно?

2021-11-02 17:15 UTC, NataliiaValko commented on models/contacts/updateById.js
> +  // console.table(await getAll())
+

2021-11-02 17:23 UTC, NataliiaValko commented on models/contacts/removeById.js
> +  const index = contacts.findIndex((contact) => contact.id.toString() === id)
Ну почему же не знаем...знаем...в джсоне с "базой данных" айдишники это намберы, но как только я сделаю патч контакта, то айдишник превратится в стрингу, чтобы потом опять таки найти этот айдишник и не заморачиваться с вопросом строка там или намбер, проще просто все привести к единой стринге. Конечно, если бы айдишник из джсона не был таким, то и проблемы такой бы не было. Но мы же форкнули именно такой джсон....

2021-11-02 17:36 UTC, NataliiaValko commented on models/contacts/getById.js
> +    (contact) => contact.id.toString() === id.toString()
Ну почему же не знаем...знаем...в джсоне с "базой данных" айдишники это намберы, но как только я сделаю патч контакта, то айдишник превратится в стрингу, чтобы потом опять таки найти этот айдишник и не заморачиваться с вопросом строка там или намбер, проще просто все привести к единой стринге. Конечно, если бы айдишник из джсона не был таким, то и проблемы такой бы не было. Но мы же форкнули именно такой джсон....

2021-11-02 17:42 UTC, NataliiaValko commented on models/contacts/getAll.js
> +  const contacts = JSON.parse(data)
переменную контакты убрала

2021-11-02 17:45 UTC, NataliiaValko commented on helpers/sendErrorReqToRes.js
> +module.exports = sendErrorReqToRes
На счет отдельного файла, то увидела у преподавателя вынесенные отдельно хендлеры и мне показалось это удобным.

2021-11-02 17:48 UTC, NataliiaValko commented on models/contacts/handlerIncorrectId.js
> +      'You entered incorrectly ID. Please check your ID and repeat the request!'
задумывалось как  "Вы ввели некорректно айди. Пожалуйста, проверьте ваш айди и повторите запрос", но если хочешь прилагательное, то ок.

2021-11-02 21:04 UTC, TViglesGoom commented on helpers/sendErrorIdToRes.js
> +  throw new NotFound(`Contact with id '${contactId}' not found`)
Переиспользуемую функцию - создавайте на здоровье. Ошибку то зачем вызывать?

2021-11-02 21:07 UTC, TViglesGoom commented on helpers/sendErrorReqToRes.js
> +module.exports = sendErrorReqToRes
А для чего вы дублируете статус код в теле ответа? И если эта ошибка именно со статусом 400, так и назовите метод соответственно. Мне вот непонятно, почему sendErrorReqToRes - это функция, которая только 1 ошибку обрабатывает

2021-11-02 21:10 UTC, TViglesGoom commented on helpers/sendSuccessToRes.js
> +module.exports = sendSuccessRes
Мне вот интересно, вот [список статус кодов](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status), вы для каждого отдельный метод сделаете? В работе может любой пригодиться. и status я могу захотеть поменять. Ещё методы создавать?

2021-11-02 21:12 UTC, TViglesGoom commented on models/contacts/removeById.js
> +  const index = contacts.findIndex((contact) => contact.id.toString() === id)
Поменяйте айдишник в json на строку. Не вижу проблемы, если вы хотите использовать строки. А вот разные типы данных в поле айди - это уже отдельная проблема, которую всё-таки надо решить.

2021-11-02 22:10 UTC, NataliiaValko commented on helpers/sendSuccessToRes.js
> +module.exports = sendSuccessRes
Влад, я правда не понимаю чем тебя так смущает эта функция? По ее названию видно, что она покрывает лишь саксесы, ссылаясь на твою ссылку, это коды 200-206. Конкретный номер статуса передается ей в виде одного из параметров.  Итого эта переиспользуемая функция покрывает все саксессные операции. Повторюсь, что нам так показал преподаватель. Если ты знаешь, что так нельзя делать или это моветон, то так и скажи "уберите это из отдельной функции и дублируйте там где требуется, потому что бла бла бла....". Потому что комментарий в стиле "я такого не видел, кто вам показал?" не дает мне возможности однозначно понять, что мне делать, а главное почему.

2021-11-02 22:11 UTC, NataliiaValko commented on models/contacts/removeById.js
> +  const index = contacts.findIndex((contact) => contact.id.toString() === id)
Я тоже не вижу проблемы в том, чтобы поменять исходники, спасибо, что разрешил их изменить.

2021-11-03 07:22 UTC, NataliiaValko commented on routes/api/contacts/contacts.js
> +  validation(contactSchema),
По ТЗ у нас разве не PUT, a PATCH?

2021-11-04 21:54 UTC, merged