hw-05-avatars
NataliiaValko/goit-nodejs-rest-api pull request #4
Opened 2021-11-17 03:16 UTC by NataliiaValko

2021-11-20 20:28 UTC, KirillKulakow commented on controllers/auth/signUp.js
> +  const avatarURL = gravatar.url('email')
здесь ты кое-что пропустила и путь к картинке не совсем корректно записывается - перепроверь

2021-11-20 20:31 UTC, KirillKulakow commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
было бы неплохо сделать проверку на MIME Type входящего файла

2021-11-20 20:32 UTC, KirillKulakow commented on controllers/auth/updateAvatar.js
> +    const avatarURL = path.join('/avatars', String(_id), fileName)
тут тоже не до конца валидная ссылка на аватарку, пропустила hostname

2021-11-20 20:32 UTC, KirillKulakow reviewed
Need some fix

2021-11-20 20:33 UTC, KirillKulakow requested changes
Need some fix

2021-11-20 20:57 UTC, NataliiaValko commented on controllers/auth/signUp.js
> +  const avatarURL = gravatar.url('email')
Путь поправила. А что пропустила? Если ты про try catch, то он в мидлваре controllerWrapper, а контроллер в нее завернут.

2021-11-20 21:06 UTC, NataliiaValko commented on controllers/auth/updateAvatar.js
> +    const avatarURL = path.join('/avatars', String(_id), fileName)
Кирилл, ниже цитата из ТЗ.
"Полученный URL  /avatars/<имя файла с расширением> сохрани в поле avatarURL пользователя". Тут вроде про хост нейм нет ничего. Все равно добавить?

2021-11-20 21:09 UTC, KirillKulakow commented on controllers/auth/signUp.js
> +  const avatarURL = gravatar.url('email')
пропущен http/https протокол

2021-11-20 21:11 UTC, KirillKulakow commented on controllers/auth/updateAvatar.js
> +    const avatarURL = path.join('/avatars', String(_id), fileName)
согласен - как бы и не по ТЗ
в принципе - окей, можно пропустить этот пункт

2021-11-20 21:19 UTC, NataliiaValko commented on controllers/auth/updateAvatar.js
> +    const avatarURL = path.join('/avatars', String(_id), fileName)
спс

2021-11-20 21:20 UTC, NataliiaValko commented on controllers/auth/signUp.js
> +  const avatarURL = gravatar.url('email')
Тут тоже пропускаем хост верно?

2021-11-21 00:41 UTC, NataliiaValko commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
добавила

2021-11-21 08:08 UTC, KirillKulakow commented on controllers/auth/signUp.js
> +  const avatarURL = gravatar.url('email')
нет - это будет глупо выглядеть

2021-11-21 08:08 UTC, KirillKulakow approved these changes

2021-11-24 00:59 UTC, merged